# Generated by Django 5.2.8 on 2025-11-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('payment_terms', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('join_date', models.DateField()),
                ('last_order', models.DateField(blank=True, null=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
