# Generated by Django 5.2.8 on 2025-11-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recipients', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('open_rate', models.FloatField(blank=True, null=True)),
                ('click_rate', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('preview_url', models.CharField(max_length=255)),
            ],
        ),
    ]
